# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_components/preference_diaglog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 720)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1261, 701))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 231, 50))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.label.setObjectName("label")
        self.output_path_label = QtWidgets.QLabel(self.frame)
        self.output_path_label.setGeometry(QtCore.QRect(260, 20, 781, 50))
        self.output_path_label.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.output_path_label.setText("")
        self.output_path_label.setObjectName("output_path_label")
        self.browse_btn = QtWidgets.QPushButton(self.frame)
        self.browse_btn.setGeometry(QtCore.QRect(1060, 20, 171, 50))
        self.browse_btn.setStyleSheet("background-color: rgb(222, 221, 218);\n"
"")
        self.browse_btn.setObjectName("browse_btn")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 80, 431, 421))
        self.frame_2.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"border-radius: 10px")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.audio_format_combo = QtWidgets.QComboBox(self.frame_2)
        self.audio_format_combo.setGeometry(QtCore.QRect(250, 240, 171, 50))
        self.audio_format_combo.setObjectName("audio_format_combo")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 231, 50))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 231, 50))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.label_3.setObjectName("label_3")
        self.audio_quality_combo = QtWidgets.QComboBox(self.frame_2)
        self.audio_quality_combo.setGeometry(QtCore.QRect(250, 100, 171, 50))
        self.audio_quality_combo.setObjectName("audio_quality_combo")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 240, 231, 50))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"")
        self.label_6.setObjectName("label_6")
        self.concurrent_combo = QtWidgets.QComboBox(self.frame_2)
        self.concurrent_combo.setGeometry(QtCore.QRect(250, 30, 171, 50))
        self.concurrent_combo.setStyleSheet("")
        self.concurrent_combo.setObjectName("concurrent_combo")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 231, 50))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.label_4.setObjectName("label_4")
        self.video_quality_combo = QtWidgets.QComboBox(self.frame_2)
        self.video_quality_combo.setGeometry(QtCore.QRect(250, 170, 171, 50))
        self.video_quality_combo.setObjectName("video_quality_combo")
        self.video_format_combo = QtWidgets.QComboBox(self.frame_2)
        self.video_format_combo.setGeometry(QtCore.QRect(250, 310, 171, 50))
        self.video_format_combo.setObjectName("video_format_combo")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 310, 231, 50))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.label_7.setObjectName("label_7")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setGeometry(QtCore.QRect(760, 570, 371, 51))
        self.buttonBox.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "  Output Directory"))
        self.browse_btn.setText(_translate("Dialog", "Browse"))
        self.label_5.setText(_translate("Dialog", "  Video Quality"))
        self.label_3.setText(_translate("Dialog", "  Concurrent Downloads"))
        self.label_6.setText(_translate("Dialog", "  Audio Format"))
        self.label_4.setText(_translate("Dialog", "  Audio Quality"))
        self.label_7.setText(_translate("Dialog", "  Video Format"))
