# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_components/preference_diaglog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 720)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(870, 670, 371, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1261, 651))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 231, 50))
        self.label.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.label.setObjectName("label")
        self.output_path_label = QtWidgets.QLabel(self.frame)
        self.output_path_label.setGeometry(QtCore.QRect(260, 20, 781, 50))
        self.output_path_label.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.output_path_label.setText("")
        self.output_path_label.setObjectName("output_path_label")
        self.browse_btn = QtWidgets.QPushButton(self.frame)
        self.browse_btn.setGeometry(QtCore.QRect(1060, 20, 171, 50))
        self.browse_btn.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.browse_btn.setObjectName("browse_btn")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 231, 50))
        self.label_3.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(280, 100, 171, 50))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", " Output Directory:"))
        self.browse_btn.setText(_translate("Dialog", "Browse"))
        self.label_3.setText(_translate("Dialog", " CPU Cores:"))
